# Generated by Django 2.2.4 on 2020-04-18 13:45

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_payoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='account_number',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='請輸入你的銀行或機構帳號'),
        ),
    ]
