# Generated by Django 2.2.4 on 2020-03-19 11:54

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_money_group', to='otree.Session')),
            ],
            options={
                'db_table': 'time_money_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_money_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'time_money_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('testQ_passed', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('testQ', otree.db.models.StringField(choices=[('1', '1'), ('26', '26'), ('56', '56'), ('64', '64')], max_length=10000, null=True, verbose_name='驗證問題：請回答 30 x 2 - 4 = ?')),
                ('accept1', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept2', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept3', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept4', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept5', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept6', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept7', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept8', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept9', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept10', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept11', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept12', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept13', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept14', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept15', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept16', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept17', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept18', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept19', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept20', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept21', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept22', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept23', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept24', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept25', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept26', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept27', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept28', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept29', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('accept30', otree.db.models.StringField(choices=[('要', '要'), ('不要', '不要')], max_length=10000, null=True, verbose_name='請問您是否要將報酬更換為上述選項')),
                ('gender', otree.db.models.StringField(choices=[('男', '男'), ('女', '女')], max_length=10000, null=True, verbose_name='1.您的性別是')),
                ('bloodgroup', otree.db.models.StringField(choices=[('A型', 'A型'), ('B型', 'B型'), ('AB型', 'AB型'), ('O型', 'O型'), ('未知', '未知'), ('以上皆非', '以上皆非')], max_length=10000, null=True, verbose_name='2.您的血型是')),
                ('taiwanese', otree.db.models.StringField(choices=[('台灣本地生', '台灣本地生'), ('非台灣本地生（例如僑生、外籍交換生學生）', '非台灣本地生（例如僑生、外籍交換生學生）')], max_length=10000, null=True, verbose_name='3.您是否為台灣本地生')),
                ('econ_manage', otree.db.models.StringField(choices=[('是', '是'), ('否', '否')], max_length=10000, null=True, verbose_name='4.您是否是經濟系或管理學院的學生')),
                ('class_num', otree.db.models.StringField(choices=[('1門', '1門'), ('2門', '2門'), ('3門', '3門'), ('4門', '4門'), ('5門', '5門'), ('超過5門', '超過5門')], max_length=10000, null=True, verbose_name='5.您修過多少門經濟學的課程')),
                ('grade', otree.db.models.StringField(choices=[('大學部1年級', '大學部1年級'), ('大學部2年級', '大學部2年級'), ('大學部3年級', '大學部3年級'), ('大學部4年級', '大學部4年級'), ('大學部5年級以上', '大學部5年級以上'), ('碩士班學生', '碩士班學生')], max_length=10000, null=True, verbose_name='6.您的系級是')),
                ('guess', otree.db.models.LongStringField(null=True, verbose_name='7.請您猜測本實驗的目的為何')),
                ('listenTime1', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime2', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime3', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime4', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime5', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime6', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime7', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime8', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime9', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime10', otree.db.models.IntegerField(default=0, null=True)),
                ('listenTime30', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration1', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration2', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration3', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration4', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration5', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration6', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration7', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration8', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration9', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration10', otree.db.models.IntegerField(default=0, null=True)),
                ('decisionduration30', otree.db.models.IntegerField(default=0, null=True)),
                ('testanscorrect', otree.db.models.IntegerField(default=1, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_money.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_money_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_money_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_money.Subsession')),
            ],
            options={
                'db_table': 'time_money_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_money.Subsession'),
        ),
    ]
