# Generated by Django 2.2.4 on 2020-03-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_money', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='testQ',
        ),
        migrations.RemoveField(
            model_name='player',
            name='testQ_passed',
        ),
    ]
