# Generated by Django 2.2.4 on 2020-03-22 10:40

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='testQ',
            field=otree.db.models.StringField(choices=[('1', '1'), ('26', '26'), ('56', '56'), ('64', '64')], max_length=10000, null=True, verbose_name='驗證問題：請回答 30 x 2 - 4 = ?'),
        ),
        migrations.AddField(
            model_name='player',
            name='testQ_passed',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
