# Generated by Django 2.2.4 on 2020-03-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_survey', '0002_auto_20200322_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='testQ_passed',
        ),
    ]
