# Generated by Django 2.2.4 on 2020-03-28 18:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_survey', '0006_auto_20200322_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='accept1',
            field=otree.db.models.StringField(choices=[('我選擇今天的報酬', '我選擇今天的報酬'), ('我選擇未來的報酬', '我選擇未來的報酬')], max_length=10000, null=True, verbose_name='請選擇您要今天或未來的報酬'),
        ),
    ]
