# Generated by Django 2.2.4 on 2020-03-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_survey', '0007_player_accept1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='accept1',
        ),
    ]
