# Generated by Django 2.2.4 on 2020-04-02 19:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='decision_duration',
            field=otree.db.models.DecimalField(default=0, null=True),
        ),
    ]
