# Generated by Django 2.2.4 on 2020-05-15 08:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_questionaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='treatment_pronoun_included',
        ),
        migrations.AddField(
            model_name='player',
            name='treatment_pronoun',
            field=otree.db.models.StringField(default='', max_length=10000, null=True),
        ),
    ]
