# Generated by Django 2.2.4 on 2020-07-02 14:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='speech_speed',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
    ]
