# Generated by Django 2.2.4 on 2020-07-02 14:25

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_questionaire', '0002_player_speech_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='speech_speed',
        ),
        migrations.AddField(
            model_name='player',
            name='treatment_speech_speed',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
    ]
