# Generated by Django 2.2.4 on 2020-04-02 20:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_questionaire', '0003_auto_20200403_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='decision_duration',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
