# Generated by Django 2.2.4 on 2020-04-02 20:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_questionaire', '0004_auto_20200403_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='decision_duration',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
    ]
