# Generated by Django 2.2.4 on 2020-04-02 20:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_survey', '0003_auto_20200403_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(choices=[('男', '男'), ('女', '女'), ('不指定', '不指定')], max_length=10000, null=True, verbose_name='1.您的性別是'),
        ),
    ]
