# Generated by Django 2.2.4 on 2020-03-25 18:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='question',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
