# Generated by Django 2.2.4 on 2020-03-25 19:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0004_auto_20200326_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='decision_duration',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gained_amount',
            field=otree.db.models.IntegerField(choices=[[1, '105元'], [2, '110元'], [3, '115元'], [4, '120元'], [5, '125元'], [6, '130元'], [7, '135元'], [8, '140元']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='get_money_now_or_future',
            field=otree.db.models.StringField(choices=[['now', '我選擇今天的報酬'], ['future', '我選擇未來的報酬']], max_length=10000, null=True, verbose_name='請選擇您要今天或未來的報酬'),
        ),
        migrations.AddField(
            model_name='player',
            name='num_listen_times',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='waiting_duration',
            field=otree.db.models.IntegerField(choices=[[1, '一週'], [2, '四周'], [3, '十二週']], null=True),
        ),
    ]
