# Generated by Django 2.2.4 on 2020-03-26 15:50

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0005_auto_20200326_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gained_amount',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='question',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='waiting_duration',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
