# Generated by Django 2.2.4 on 2020-03-26 19:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0006_auto_20200326_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='waiting_duration',
        ),
        migrations.AddField(
            model_name='player',
            name='waiting_period',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
