# Generated by Django 2.2.4 on 2020-03-26 20:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0008_auto_20200327_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gained_amount',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='waiting_period',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
