# Generated by Django 2.2.4 on 2020-03-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0009_auto_20200327_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='question',
        ),
    ]
