# Generated by Django 2.2.4 on 2020-03-28 17:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0010_remove_player_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='selecged_get_money_now',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='selected_gained_amount',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='selected_get_waiting_period',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='selected_round',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
