# Generated by Django 2.2.4 on 2020-03-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0012_auto_20200329_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='selected_gained_amount',
        ),
        migrations.RemoveField(
            model_name='subsession',
            name='selected_get_money_now',
        ),
        migrations.RemoveField(
            model_name='subsession',
            name='selected_round',
        ),
        migrations.RemoveField(
            model_name='subsession',
            name='selected_waiting_period',
        ),
    ]
