# Generated by Django 2.2.4 on 2020-03-29 09:07

from django.db import migrations
import otree.db.models
import rounds_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0013_auto_20200329_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='get_money_now_or_future',
            field=otree.db.models.StringField(choices=[[rounds_test.models.OptionOfGetMoney('選擇今天的報酬'), '我選擇今天的報酬'], [rounds_test.models.OptionOfGetMoney('選擇未來的報酬'), '我選擇未來的報酬']], max_length=10000, null=True, verbose_name='請選擇您要今天或未來的報酬'),
        ),
    ]
