# Generated by Django 2.2.4 on 2020-03-29 10:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0019_auto_20200329_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='selected_questionare',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
