# Generated by Django 2.2.4 on 2020-03-29 11:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0020_subsession_selected_questionare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='selected_questionare',
        ),
        migrations.AddField(
            model_name='player',
            name='is_selected',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
