# Generated by Django 2.2.4 on 2020-04-01 18:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds_test', '0023_player_treatment_subject_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='treatment_subject_included',
        ),
        migrations.AddField(
            model_name='player',
            name='treatment_pronoun_included',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
