# Generated by Django 2.2.4 on 2020-04-03 08:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='decision_duration',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gained_amount',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='get_money_now_or_future',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='請選擇您要今天或未來的報酬'),
        ),
        migrations.AddField(
            model_name='player',
            name='num_listen_times',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='treatment_pronoun_included',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='waiting_period',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
