# Generated by Django 2.2.4 on 2020-04-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EconExp1_TimePrefPronoun1_intro', '0002_auto_20200403_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
